# Generated by Django 4.2.6 on 2025-01-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='tag_status',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='taken_or_released_status',
        ),
    ]
