# Generated by Django 4.2.6 on 2025-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchDetails', '0002_remove_catch_tag_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='tag_status',
            field=models.CharField(choices=[(1, 'Tagged'), (2, 'Untagged'), (3, 'Newly Tagged Today'), (4, 'Not Given')], default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='catch',
            name='taken_or_released_status',
            field=models.CharField(choices=[(1, 'Taken'), (2, 'Released'), (3, 'Not Given')], default=1, max_length=3),
        ),
    ]
