# Generated by Django 4.2.6 on 2025-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchDetails', '0003_catch_tag_status_catch_taken_or_released_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='tag_status',
            field=models.IntegerField(choices=[(1, 'Tagged'), (2, 'Untagged'), (3, 'Newly Tagged Today'), (4, 'Not Given')], default=4),
        ),
        migrations.AlterField(
            model_name='catch',
            name='taken_or_released_status',
            field=models.IntegerField(choices=[(1, 'Taken'), (2, 'Released'), (3, 'Not Given')], default=3),
        ),
    ]
